# Generated by Django 6.0 on 2025-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debateturn',
            options={},
        ),
        migrations.RenameField(
            model_name='debateturn',
            old_name='user',
            new_name='speaker',
        ),
        migrations.RenameField(
            model_name='debateturn',
            old_name='argument_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='debateturn',
            name='turn_number',
            field=models.PositiveIntegerField(),
        ),
    ]
