# Generated by Django 6.0 on 2025-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_debateturn_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debateturn',
            options={'ordering': ['turn_number']},
        ),
        migrations.AddField(
            model_name='debateroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='api.userprofile'),
        ),
        migrations.AddIndex(
            model_name='debateroom',
            index=models.Index(fields=['room_code'], name='api_debater_room_co_4a21f6_idx'),
        ),
        migrations.AddIndex(
            model_name='debateturn',
            index=models.Index(fields=['room', 'turn_number'], name='api_debatet_room_id_9acd8b_idx'),
        ),
    ]
